// Données mock centralisées - Bacheliers (utilisateurs)
import type { Bachelier } from '../../types';

export const mockBacheliers: Bachelier[] = [
  {
    idBachelier: 1,
    nom: 'Mensah',
    prenom: 'Kofi',
    email: 'kofi.mensah@gmail.com',
    telephone: '+228 90 12 34 56',
    serieBac: 'C',
    moyenneBac: 15.5,
    matieresPrincipales: 'Mathématiques, Physique',
    budgetMax: 800000,
    objectifsProfessionnels: 'Devenir ingénieur en informatique et contribuer au développement technologique du Togo',
    dateInscription: '2025-01-15T10:00:00Z',
  },
  {
    idBachelier: 2,
    nom: 'Amegah',
    prenom: 'Ama',
    email: 'ama.amegah@yahoo.fr',
    telephone: '+228 91 23 45 67',
    serieBac: 'D',
    moyenneBac: 14.2,
    matieresPrincipales: 'SVT, Chimie',
    budgetMax: 600000,
    objectifsProfessionnels: 'Médecin généraliste pour servir dans les zones rurales',
    dateInscription: '2025-01-14T09:00:00Z',
  },
  {
    idBachelier: 3,
    nom: 'Koffi',
    prenom: 'Esso',
    email: 'esso.koffi@outlook.com',
    telephone: '+228 92 34 56 78',
    serieBac: 'A4',
    moyenneBac: 16.0,
    matieresPrincipales: 'Philosophie, Anglais',
    budgetMax: 450000,
    objectifsProfessionnels: 'Devenir avocat spécialisé en droit OHADA',
    dateInscription: '2025-01-13T14:00:00Z',
  },
  {
    idBachelier: 4,
    nom: 'Agbeko',
    prenom: 'Yao',
    email: 'yao.agbeko@gmail.com',
    telephone: '+228 93 45 67 89',
    serieBac: 'G2',
    moyenneBac: 13.8,
    matieresPrincipales: 'Comptabilité, Économie',
    budgetMax: 550000,
    objectifsProfessionnels: 'Expert-comptable dans un cabinet à Lomé',
    dateInscription: '2025-01-12T11:00:00Z',
  },
  {
    idBachelier: 5,
    nom: 'Dossou',
    prenom: 'Akouvi',
    email: 'akouvi.dossou@email.tg',
    telephone: '+228 94 56 78 90',
    serieBac: 'C',
    moyenneBac: 17.5,
    matieresPrincipales: 'Mathématiques, Informatique',
    budgetMax: 1200000,
    objectifsProfessionnels: 'Data Scientist dans une entreprise tech africaine',
    dateInscription: '2025-01-11T08:00:00Z',
  },
  {
    idBachelier: 6,
    nom: 'Ayeva',
    prenom: 'Mawusi',
    email: 'mawusi.ayeva@gmail.com',
    telephone: '+228 95 67 89 01',
    serieBac: 'G2',
    moyenneBac: 12.5,
    matieresPrincipales: 'Gestion, Commerce',
    budgetMax: 500000,
    objectifsProfessionnels: 'Gestionnaire d\'entreprise et entrepreneure',
    dateInscription: '2025-01-10T16:00:00Z',
  },
  {
    idBachelier: 7,
    nom: 'Eklou',
    prenom: 'Koku',
    email: 'koku.eklou@yahoo.fr',
    telephone: '+228 96 78 90 12',
    serieBac: 'C',
    moyenneBac: 18.2,
    matieresPrincipales: 'Physique, Chimie',
    budgetMax: 1500000,
    objectifsProfessionnels: 'Chercheur en énergies renouvelables',
    dateInscription: '2025-01-09T09:30:00Z',
  },
  {
    idBachelier: 8,
    nom: 'Gbadamassi',
    prenom: 'Adjoa',
    email: 'adjoa.gbadamassi@gmail.com',
    telephone: '+228 97 89 01 23',
    serieBac: 'D',
    moyenneBac: 15.8,
    matieresPrincipales: 'Biologie, Chimie',
    budgetMax: 900000,
    objectifsProfessionnels: 'Pharmacienne et chercheuse en pharmacologie',
    dateInscription: '2025-01-08T13:00:00Z',
  },
  {
    idBachelier: 9,
    nom: 'Lawson',
    prenom: 'Edem',
    email: 'edem.lawson@outlook.com',
    telephone: '+228 98 90 12 34',
    serieBac: 'E',
    moyenneBac: 14.5,
    matieresPrincipales: 'Mathématiques, Dessin technique',
    budgetMax: 700000,
    objectifsProfessionnels: 'Architecte spécialisé en urbanisme africain',
    dateInscription: '2025-01-07T10:00:00Z',
  },
  {
    idBachelier: 10,
    nom: 'Amedegnato',
    prenom: 'Sena',
    email: 'sena.amedegnato@gmail.com',
    telephone: '+228 99 01 23 45',
    serieBac: 'C',
    moyenneBac: 16.8,
    matieresPrincipales: 'Mathématiques, Informatique',
    budgetMax: 1000000,
    objectifsProfessionnels: 'Ingénieur en cybersécurité',
    dateInscription: '2025-01-06T15:00:00Z',
  },
  {
    idBachelier: 11,
    nom: 'Adjakly',
    prenom: 'Kossi',
    email: 'kossi.adjakly@yahoo.fr',
    telephone: '+228 90 23 45 67',
    serieBac: 'F3',
    moyenneBac: 13.2,
    matieresPrincipales: 'Électrotechnique, Physique',
    budgetMax: 650000,
    objectifsProfessionnels: 'Ingénieur électricien dans le secteur énergétique',
    dateInscription: '2025-01-05T11:00:00Z',
  },
  {
    idBachelier: 12,
    nom: 'Dogbe',
    prenom: 'Akossiwa',
    email: 'akossiwa.dogbe@email.tg',
    telephone: '+228 91 34 56 78',
    serieBac: 'A4',
    moyenneBac: 15.0,
    matieresPrincipales: 'Anglais, Allemand',
    budgetMax: 400000,
    objectifsProfessionnels: 'Traductrice internationale et diplomate',
    dateInscription: '2025-01-04T09:00:00Z',
  },
];
