// Mocks centralisés pour les candidatures (utilisés par les pages en dev)
export const mockCandidatures = [
    {
        id: 1,
        numeroCandidature: 'CAND-2026-001',
        nom: 'AGBEKO',
        prenom: 'Kofi',
        email: 'kofi.agbeko@email.com',
        telephone: '+228 90 12 34 56',
        dateNaissance: '2005-03-15',
        sexe: 'M',
        serieBac: 'C',
        moyenneBac: 14.5,
        domaine: 'Sciences et Technologies',
        parcours: 'Informatique',
        filiere: 'Génie Logiciel',
        dateSoumission: '2026-02-01',
        statut: 'SOUMISE',
    },
    {
        id: 2,
        numeroCandidature: 'CAND-2026-002',
        nom: 'MENSAH',
        prenom: 'Ama',
        email: 'ama.mensah@email.com',
        telephone: '+228 91 23 45 67',
        dateNaissance: '2004-07-22',
        sexe: 'F',
        serieBac: 'D',
        moyenneBac: 15.2,
        domaine: 'Sciences et Technologies',
        parcours: 'Informatique',
        filiere: 'Réseaux & Systèmes',
        dateSoumission: '2026-02-02',
        statut: 'EN_COURS',
    },
    {
        id: 3,
        numeroCandidature: 'CAND-2026-003',
        nom: 'KODJO',
        prenom: 'Yao',
        email: 'yao.kodjo@email.com',
        telephone: '+228 92 34 56 78',
        dateNaissance: '2005-11-08',
        sexe: 'M',
        serieBac: 'C',
        moyenneBac: 16.8,
        domaine: 'Sciences et Technologies',
        parcours: 'Informatique',
        filiere: 'Intelligence Artificielle',
        dateSoumission: '2026-02-03',
        statut: 'ACCEPTEE',
    },
    {
        id: 4,
        numeroCandidature: 'CAND-2026-004',
        nom: 'ADOM',
        prenom: 'Akossiwa',
        email: 'akossiwa.adom@email.com',
        telephone: '+228 93 45 67 89',
        dateNaissance: '2004-01-30',
        sexe: 'F',
        serieBac: 'D',
        moyenneBac: 13.9,
        domaine: 'Sciences et Technologies',
        parcours: 'Mathématiques Appliquées',
        filiere: 'Data Science',
        dateSoumission: '2026-02-04',
        statut: 'EN_ATTENTE_CONCOURS',
    },
    {
        id: 5,
        numeroCandidature: 'CAND-2026-005',
        nom: 'AMEGAH',
        prenom: 'Kossi',
        email: 'kossi.amegah@email.com',
        telephone: '+228 94 56 78 90',
        dateNaissance: '2005-06-12',
        sexe: 'M',
        serieBac: 'C',
        moyenneBac: 12.5,
        domaine: 'Sciences Économiques et Gestion',
        parcours: 'Gestion des Entreprises',
        filiere: 'Finance',
        dateSoumission: '2026-02-05',
        statut: 'REFUSEE',
    },
    {
        id: 6,
        numeroCandidature: 'CAND-2026-006',
        nom: 'AYIVI',
        prenom: 'Essi',
        email: 'essi.ayivi@email.com',
        telephone: '+228 95 67 89 01',
        dateNaissance: '2005-09-20',
        sexe: 'F',
        serieBac: 'D',
        moyenneBac: 14.1,
        domaine: 'Sciences Économiques et Gestion',
        parcours: 'Gestion des Entreprises',
        filiere: 'Comptabilité',
        dateSoumission: '2026-02-06',
        statut: 'SOUMISE',
    },
    {
        id: 7,
        numeroCandidature: 'CAND-2026-007',
        nom: 'DZIFA',
        prenom: 'Ablam',
        email: 'ablam.dzifa@email.com',
        telephone: '+228 96 78 90 12',
        dateNaissance: '2004-12-05',
        sexe: 'M',
        serieBac: 'C',
        moyenneBac: 17.2,
        domaine: 'Sciences et Technologies',
        parcours: 'Informatique',
        filiere: 'Génie Logiciel',
        dateSoumission: '2026-02-07',
        statut: 'ACCEPTEE',
    },
];

export const mockParcours = ['Tous les parcours', 'Informatique', 'Mathématiques Appliquées', 'Gestion des Entreprises'];
export const mockFilieres = ['Toutes les filières', 'Génie Logiciel', 'Réseaux & Systèmes', 'Intelligence Artificielle', 'Data Science', 'Finance', 'Comptabilité'];

export default mockCandidatures;
