// Données mock centralisées - Établissements
import type { Etablissement } from '../../types';

export const mockEtablissements: Etablissement[] = [
  {
    idEtablissement: 1,
    nom: 'Université de Lomé',
    type: 'Université',
    localisation: 'Maritime',
    description: 'Première université publique du Togo, fondée en 1970. Elle offre des formations dans tous les domaines académiques.',
    contact: 'Direction des Études',
    email: 'contact@univ-lome.tg',
    telephone: '+228 22 25 50 94',
    siteWeb: 'https://www.univ-lome.tg',
  },
  {
    idEtablissement: 2,
    nom: 'Université de Kara',
    type: 'Université',
    localisation: 'Kara',
    description: 'Deuxième université publique du Togo, située dans la région de la Kara.',
    contact: 'Secrétariat Général',
    email: 'contact@univ-kara.tg',
    telephone: '+228 26 60 01 23',
    siteWeb: 'https://www.univ-kara.tg',
  },
  {
    idEtablissement: 3,
    nom: 'EAMAU',
    type: 'École',
    localisation: 'Maritime',
    description: 'École Africaine des Métiers de l\'Architecture et de l\'Urbanisme, institution panafricaine basée à Lomé.',
    contact: 'Direction Académique',
    email: 'info@eamau.org',
    telephone: '+228 22 21 62 53',
    siteWeb: 'https://www.eamau.org',
  },
  {
    idEtablissement: 4,
    nom: 'ESIBA',
    type: 'École',
    localisation: 'Maritime',
    description: 'École Supérieure d\'Informatique et de Business Administration.',
    contact: 'Service Admissions',
    email: 'contact@esiba.tg',
    telephone: '+228 22 26 45 78',
    siteWeb: 'https://www.esiba.tg',
  },
  {
    idEtablissement: 5,
    nom: 'IAM Lomé',
    type: 'Institut',
    localisation: 'Maritime',
    description: 'Institut Africain de Management, école de commerce et de gestion.',
    contact: 'Direction des Programmes',
    email: 'info@iam-lome.tg',
    telephone: '+228 22 20 30 40',
    siteWeb: 'https://www.iam-lome.tg',
  },
  {
    idEtablissement: 6,
    nom: 'UCAO-UUT',
    type: 'Université',
    localisation: 'Maritime',
    description: 'Université Catholique de l\'Afrique de l\'Ouest - Unité Universitaire du Togo.',
    contact: 'Rectorat',
    email: 'contact@ucao-uut.tg',
    telephone: '+228 22 21 30 45',
    siteWeb: 'https://www.ucao-uut.tg',
  },
  {
    idEtablissement: 7,
    nom: 'ENSI',
    type: 'École',
    localisation: 'Maritime',
    description: 'École Nationale Supérieure d\'Ingénieurs, formation d\'ingénieurs dans divers domaines.',
    contact: 'Direction de l\'École',
    email: 'ensi@univ-lome.tg',
    telephone: '+228 22 25 67 89',
    siteWeb: 'https://ensi.univ-lome.tg',
  },
  {
    idEtablissement: 8,
    nom: 'ESA - École Supérieure d\'Agronomie',
    type: 'École',
    localisation: 'Maritime',
    description: 'École de formation en sciences agronomiques de l\'Université de Lomé.',
    contact: 'Service Scolarité',
    email: 'esa@univ-lome.tg',
    telephone: '+228 22 25 41 10',
    siteWeb: 'https://esa.univ-lome.tg',
  },
  {
    idEtablissement: 9,
    nom: 'CERSA Kpalimé',
    type: 'Institut',
    localisation: 'Plateaux',
    description: 'Centre d\'Études et de Recherche en Sciences Agronomiques de Kpalimé.',
    contact: 'Direction du Centre',
    email: 'cersa@agriculture.gouv.tg',
    telephone: '+228 24 41 01 23',
    siteWeb: 'https://www.cersa.tg',
  },
  {
    idEtablissement: 10,
    nom: 'INFA Tové',
    type: 'Institut',
    localisation: 'Plateaux',
    description: 'Institut National de Formation Agricole de Tové, formation technique agricole.',
    contact: 'Administration',
    email: 'infa@agriculture.gouv.tg',
    telephone: '+228 24 40 02 34',
    siteWeb: 'https://www.infa-tove.tg',
  },
];
