// Données mock centralisées - Logs d'activité
import type { Log } from '../logs';

export const mockLogs: Log[] = [
  {
    id: 1,
    date: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    type: 'connexion',
    action: 'Connexion réussie',
    description: 'L\'administrateur s\'est connecté avec succès',
    utilisateur: 'Admin Principal',
    ip: '192.168.1.100',
  },
  {
    id: 2,
    date: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    type: 'creation',
    action: 'Création d\'utilisateur',
    description: 'Nouvel utilisateur créé: Kofi Mensah',
    utilisateur: 'Admin Principal',
    entite: 'Bachelier',
    entiteId: 1,
  },
  {
    id: 3,
    date: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    type: 'modification',
    action: 'Modification d\'établissement',
    description: 'Mise à jour des informations de l\'Université de Lomé',
    utilisateur: 'Admin Principal',
    entite: 'Etablissement',
    entiteId: 1,
    details: { champs: ['description', 'contact'] },
  },
  {
    id: 4,
    date: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    type: 'validation',
    action: 'Validation d\'inscription',
    description: 'Inscription validée pour le programme Informatique',
    utilisateur: 'Admin Principal',
    entite: 'Inscription',
    entiteId: 45,
  },
  {
    id: 5,
    date: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    type: 'suppression',
    action: 'Suppression de programme',
    description: 'Programme "Techniques anciennes" supprimé',
    utilisateur: 'Admin Principal',
    entite: 'Programme',
    entiteId: 99,
  },
  {
    id: 6,
    date: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    type: 'export',
    action: 'Export de données',
    description: 'Export de la liste des bacheliers au format Excel',
    utilisateur: 'Admin Principal',
    details: { format: 'xlsx', lignes: 250 },
  },
  {
    id: 7,
    date: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    type: 'consultation',
    action: 'Consultation de statistiques',
    description: 'Consultation du tableau de bord principal',
    utilisateur: 'Admin Principal',
    ip: '192.168.1.100',
  },
  {
    id: 8,
    date: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    type: 'rejet',
    action: 'Rejet de demande',
    description: 'Demande d\'inscription rejetée - dossier incomplet',
    utilisateur: 'Admin Principal',
    entite: 'Inscription',
    entiteId: 42,
    details: { motif: 'Documents manquants' },
  },
  {
    id: 9,
    date: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    type: 'import',
    action: 'Import de données',
    description: 'Import de 50 nouveaux programmes',
    utilisateur: 'Admin Principal',
    details: { format: 'csv', lignes: 50 },
  },
  {
    id: 10,
    date: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    type: 'deconnexion',
    action: 'Déconnexion',
    description: 'Fin de session administrateur',
    utilisateur: 'Admin Principal',
    ip: '192.168.1.100',
  },
  {
    id: 11,
    date: new Date(Date.now() - 26 * 60 * 60 * 1000).toISOString(),
    type: 'creation',
    action: 'Création d\'établissement',
    description: 'Nouvel établissement ajouté: ESIBA',
    utilisateur: 'Admin Principal',
    entite: 'Etablissement',
    entiteId: 4,
  },
  {
    id: 12,
    date: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    type: 'modification',
    action: 'Modification des paramètres',
    description: 'Mise à jour des paramètres de notification',
    utilisateur: 'Admin Principal',
    entite: 'Paramètres',
    details: { section: 'notifications', active: true },
  },
];
