// Données mock centralisées - Programmes
import type { Programme } from '../../types';

export const mockProgrammes: Programme[] = [
  {
    idProgramme: 1,
    nomProgramme: 'Informatique et Systèmes d\'Information',
    domaine: 'Informatique',
    niveau: 'Licence',
    fraisScolarite: 350000,
    conditionsAdmission: 'Bac C, D, E ou F2/F3, dossier et entretien',
    duree: 3,
    debouchesProfessionnels: 'Développeur, Analyste programmeur, Administrateur systèmes',
    idEtablissement: 1,
    etablissementNom: 'Université de Lomé',
  },
  {
    idProgramme: 2,
    nomProgramme: 'Intelligence Artificielle et Data Science',
    domaine: 'Informatique',
    niveau: 'Master',
    fraisScolarite: 850000,
    conditionsAdmission: 'Licence en informatique ou mathématiques, bon niveau en programmation',
    duree: 2,
    debouchesProfessionnels: 'Data Scientist, Ingénieur IA, Chef de projet Big Data',
    idEtablissement: 1,
    etablissementNom: 'Université de Lomé',
  },
  {
    idProgramme: 3,
    nomProgramme: 'Gestion des Entreprises',
    domaine: 'Commerce & Management',
    niveau: 'Licence',
    fraisScolarite: 450000,
    conditionsAdmission: 'Bac toutes séries, étude de dossier',
    duree: 3,
    debouchesProfessionnels: 'Assistant manager, Chargé de clientèle, Gestionnaire administratif',
    idEtablissement: 5,
    etablissementNom: 'IAM Lomé',
  },
  {
    idProgramme: 4,
    nomProgramme: 'MBA Management',
    domaine: 'Commerce & Management',
    niveau: 'Master',
    fraisScolarite: 1500000,
    conditionsAdmission: 'Bac+4 minimum, 2 ans d\'expérience professionnelle',
    duree: 2,
    debouchesProfessionnels: 'Directeur général, Consultant stratégique, Entrepreneur',
    idEtablissement: 5,
    etablissementNom: 'IAM Lomé',
  },
  {
    idProgramme: 5,
    nomProgramme: 'Génie Civil',
    domaine: 'Ingénierie',
    niveau: 'Licence',
    fraisScolarite: 500000,
    conditionsAdmission: 'Bac C, D, E ou F4, bonnes bases en mathématiques',
    duree: 3,
    debouchesProfessionnels: 'Technicien BTP, Conducteur de travaux, Dessinateur projeteur',
    idEtablissement: 7,
    etablissementNom: 'ENSI',
  },
  {
    idProgramme: 6,
    nomProgramme: 'Ingénierie Électrique',
    domaine: 'Ingénierie',
    niveau: 'Master',
    fraisScolarite: 900000,
    conditionsAdmission: 'Licence en génie électrique ou physique',
    duree: 2,
    debouchesProfessionnels: 'Ingénieur électricien, Chef de projet, Ingénieur R&D',
    idEtablissement: 7,
    etablissementNom: 'ENSI',
  },
  {
    idProgramme: 7,
    nomProgramme: 'Droit Privé',
    domaine: 'Droit',
    niveau: 'Licence',
    fraisScolarite: 300000,
    conditionsAdmission: 'Bac A, B ou G, bonnes capacités rédactionnelles',
    duree: 3,
    debouchesProfessionnels: 'Assistant juridique, Clerc de notaire, Gestionnaire de contentieux',
    idEtablissement: 1,
    etablissementNom: 'Université de Lomé',
  },
  {
    idProgramme: 8,
    nomProgramme: 'Droit des Affaires OHADA',
    domaine: 'Droit',
    niveau: 'Master',
    fraisScolarite: 750000,
    conditionsAdmission: 'Licence en droit, maîtrise du français',
    duree: 2,
    debouchesProfessionnels: 'Juriste d\'entreprise, Avocat d\'affaires, Conseiller juridique',
    idEtablissement: 6,
    etablissementNom: 'UCAO-UUT',
  },
  {
    idProgramme: 9,
    nomProgramme: 'Architecture',
    domaine: 'Architecture',
    niveau: 'Master',
    fraisScolarite: 1200000,
    conditionsAdmission: 'Bac C, D, E ou F4, test d\'aptitude graphique',
    duree: 5,
    debouchesProfessionnels: 'Architecte, Urbaniste, Designer d\'intérieur',
    idEtablissement: 3,
    etablissementNom: 'EAMAU',
  },
  {
    idProgramme: 10,
    nomProgramme: 'Médecine Générale',
    domaine: 'Santé',
    niveau: 'Doctorat',
    fraisScolarite: 450000,
    conditionsAdmission: 'Bac C ou D avec mention, concours d\'entrée',
    duree: 7,
    debouchesProfessionnels: 'Médecin généraliste, Spécialiste, Chercheur en médecine',
    idEtablissement: 1,
    etablissementNom: 'Université de Lomé',
  },
  {
    idProgramme: 11,
    nomProgramme: 'Sciences Agronomiques',
    domaine: 'Agriculture',
    niveau: 'Licence',
    fraisScolarite: 320000,
    conditionsAdmission: 'Bac D, C ou E, intérêt pour l\'agriculture',
    duree: 3,
    debouchesProfessionnels: 'Technicien agricole, Conseiller agricole, Agent de développement rural',
    idEtablissement: 8,
    etablissementNom: 'ESA - École Supérieure d\'Agronomie',
  },
  {
    idProgramme: 12,
    nomProgramme: 'Informatique de Gestion',
    domaine: 'Informatique',
    niveau: 'Licence',
    fraisScolarite: 550000,
    conditionsAdmission: 'Bac C, D, G2 ou F, test d\'entrée',
    duree: 3,
    debouchesProfessionnels: 'Analyste fonctionnel, Développeur ERP, Chef de projet IT',
    idEtablissement: 4,
    etablissementNom: 'ESIBA',
  },
];
